// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Online_mobile_store.Models;

public partial class mobilestore_dbContext : DbContext
{
    public mobilestore_dbContext()
    {
    }

    public mobilestore_dbContext(DbContextOptions<mobilestore_dbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<Users_Product> Users_Products { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer("server=.;Initial Catalog=mobilestore_db;Integrated Security=True;TrustServerCertificate=True;");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Product>(entity =>
        {
            entity.HasOne(d => d.seller).WithMany(p => p.Products).HasConstraintName("FK_Products_Users");
        });

        modelBuilder.Entity<Users_Product>(entity =>
        {
            entity.HasKey(e => new { e.user_id, e.prod_id }).HasName("PK_Selected_Products");

            entity.HasOne(d => d.prod).WithMany(p => p.Users_Products)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Users_Products_Products");

            entity.HasOne(d => d.user).WithMany(p => p.Users_Products)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Users_Products_Users");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}