// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Online_mobile_store.Models;

public partial class Product
{
    [Key]
    public int prod_id { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    [Required(ErrorMessage = "Name is required")]
    public string prod_name { get; set; }

    [Column(TypeName = "money")]
    [Required]
	[Range(1, int.MaxValue,ErrorMessage ="Price Should Be Grater Than 1")]
	public decimal? price { get; set; }
    [Required]
	[Range(0, int.MaxValue)]
	public int? quantity { get; set; }
    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string type { get; set; }

    public int? sellerid { get; set; }
    [StringLength(50)]
    [Unicode(false)]
    
    public string image { get; set; }

    [InverseProperty("prod")]
    public virtual ICollection<Users_Product> Users_Products { get; set; } = new List<Users_Product>();

    [ForeignKey("sellerid")]
    [InverseProperty("Products")]
    public virtual User seller { get; set; }
}