// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Online_mobile_store.Models;


public partial class User
{
    [Key]
    public int ID { get; set; }
    [Required]
    [Unicode(false)]
    [StringLength(20, MinimumLength = 3, ErrorMessage = "Username must be between 3 and 20 characters")]
    public string UserName { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    [Required(ErrorMessage = "Please enter an email address")]
    [EmailAddress(ErrorMessage = "Please enter a valid email address")]
    public string Email { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    [RegularExpression(@"^(?=.*[A-Za-z])(?=.*\d)(?=.*[^A-Za-z0-9]).{8,20}$",
    ErrorMessage = "Password must be between 8 and 20 characters and contain at least one letter, one digit, and one special character.")]


    public string Password { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    [Required]
    public string Gender { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    [Required]
    public string Role { get; set; }

    [InverseProperty("seller")]
    public virtual ICollection<Product> Products { get; set; } = new List<Product>();

    [InverseProperty("user")]
    public virtual ICollection<Users_Product> Users_Products { get; set; } = new List<Users_Product>();
}