// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Online_mobile_store.Models;

[PrimaryKey("user_id", "prod_id")]
public partial class Users_Product
{
    [Key]
    public int user_id { get; set; }

    [Key]
    public int prod_id { get; set; }

    public int? selected_quantity { get; set; }

    public DateOnly? date { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string status { get; set; }

    [ForeignKey("prod_id")]
    [InverseProperty("Users_Products")]
    public virtual Product prod { get; set; }

    [ForeignKey("user_id")]
    [InverseProperty("Users_Products")]
    public virtual User user { get; set; }
}